### ISSUE TITLE
exitProcessOnClose : App not responding in some cases

### ISSUE THREAD

**Issue by kwisatz** [neutralinojs/neutralino.js#102]
I have set `"exitProcessOnClose": true` in `neutralino.config.js`. 

On my Windows 10 installation, from clicking to the app closing, it takes 2-3 seconds, which appears as very long.
However, on a client's Windows 10 installation, it takes up to 30 seconds (and the app showing as "Not Responding") before it actually closes. 

What could cause these differences in behavior and how could I further investigate?

**Comment by benjammin4dayz** [comment]
> I have set `"exitProcessOnClose": true` in `neutralino.config.js`.
> 
> On my Windows 10 installation, from clicking to the app closing, it takes 2-3 seconds, which appears as very long. However, on a client's Windows 10 installation, it takes up to 30 seconds (and the app showing as "Not Responding") before it actually closes.
> 
> What could cause these differences in behavior and how could I further investigate?

Hey there! I believe this is a known issue with Neutralino. (see: https://github.com/neutralinojs/neutralinojs/issues/1179)

I lack the expertise to answer your question directly but there is a simple workaround outlined in [this comment](https://github.com/neutralinojs/neutralinojs/issues/1179#issuecomment-1946188341).

**Comment by kwisatz** [comment]
Seems like my ticket is indeed a duplicate. I searched for similar tickets, not apparently missed that one.

In any case, with the workaround described, which comes with the sample app when you create one, the app wouldn't close at all for me.

**Comment by kwisatz** [comment]
Closing as duplicate of #1179
