### ISSUE TITLE
Applying a direct Copy option next to the link provided on the main page

### ISSUE THREAD

**Issue by DaanishShaikh** [neutralinojs/neutralino.js#111]
The link npm install -g @neutralinojs/neu provided in the first page of the website has to be selected and copied. 
This make it easier to copy, we can add a button next to it, which when clicked will automatically copy the link.
This will expand the reach of the link as it will be more easily accessible i.e. with just a click of a button.
<img width="946" alt="nuetralinho" src="https://github.com/neutralinojs/neutralino.js/assets/148933765/93c041a5-abb5-441e-a682-2ad2dd1d4c4c">
<img width="946" alt="image" src="https://github.com/neutralinojs/neutralino.js/assets/148933765/8d98e735-180e-44ba-8a5a-97bfbccee5e4">

**Comment by ydv-ankit** [comment]
yes that can help users to use with ease
i'm working on it

**Comment by akshatbhj** [comment]
Hi Daanish, is this issue still open, ( if yes ) I would like to work on it.

**Comment by DaanishShaikh** [comment]
hello Akshat, yes it is still open. go ahead with it.

**Comment by DaanishShaikh** [comment]
i think it is closed now as i see a copy button on the link. 
![image](https://github.com/user-attachments/assets/7bcd67ab-3b50-47ee-84f4-bb5395ef0cdd)

**Comment by akshatbhj** [comment]
Okay @DaanishShaikh, thanks for replying.

**Comment by shalithasuranga** [comment]
Let's close this issue then. Thanks for creating this issue and starting a discussion :tada:

**Comment by DaanishShaikh** [comment]
> Let's close this issue then. Thanks for creating this issue and starting a discussion 🎉

my pleasure!!
