### ISSUE TITLE
setDraggableRegion not working on Mac in 3.0.0

### ISSUE THREAD

**Issue by Blatman** [neutralinojs/neutralino.js#16]
NS 3.0.0pre  NC 1.5.0 latest

10.13 (Safari 13)  10.14 (Safari 14)

setDraggableRegion does not work with pointerevents on Mac. I had it going on 2.6.0 but doesn't appear to work on 2.80 and 3.0.0pre. I notice that the C++ code now use pointerevents rather than mouse although Safari should support these.

I tried the old mouse event code in 3.0.0 pre and the draggable works albeit shonky as before. The window.move events show in the inspector but with the pointerevent code the window.move events do not appear and no dragging occurs.

If I view the main window object the MouseEvent exists but not a sign of pointer events.

This url refers to a bug that may be relevant -
https://bugs.webkit.org/show_bug.cgi?id=202287

**Comment by danisss9** [comment]
_mouseevents_ has a bug on Windows when dragging outside the window, so maybe Neutralino needs to use both: _mousevents_ for Mac and _pointerevents_ for Windows and Linux. 

I had multiple bad experiences waiting for the Safari team to fix bugs 😢

**Comment by Blatman** [comment]
Update:  Found setDraggableRegion to be working on M1 mac running Monterey 12.1 - I can only assume that Safari 15 has made the difference. Safari 14 was supposed to have supported pointerevents but maybe it was only fixed in 15 so looks as though setDraggableRegion using pointervents will only be good for Safari 15 onwards.

**Comment by Blatman** [comment]
I am inclined to close this issue since using Safari 15 (Catalina onward) works OK and most dev support is now leaning toward Catalina or later.
