### ISSUE TITLE
404 URL 

### ISSUE THREAD

**Issue by kerolloz** [neutralinojs/neutralino.js#25]
this [URL](https://neutralino.js.org/docs/api/introduction) gives a Page Not Found 

![image](https://user-images.githubusercontent.com/36763164/140946571-25950640-3cc3-4f1b-adf7-ba446541eace.png)

![Screenshot from 2021-11-09 16-51-59](https://user-images.githubusercontent.com/36763164/140946750-d277e593-dad7-4a48-bcfe-0d1d9a4c391c.png)

**Comment by shalithasuranga** [comment]
Hey.. thanks for reporting the issue. I've update the repo's URL and a contributor fixed readme's URL via https://github.com/neutralinojs/neutralino.js/pull/24
