### ISSUE TITLE
Make the client code npm package

### ISSUE THREAD

**Issue by spiotr12** [neutralinojs/neutralino.js#36]
Could this be an npm package?

**Comment by roblet404** [comment]
it already is an npm package

`npm install -g @neutralinojs/neu`

https://www.npmjs.com/package/@neutralinojs/neu

**Comment by pathange-s** [comment]
He's talking about the client library I guess. @spiotr12 right ?

**Comment by shalithasuranga** [comment]
Please check: https://www.npmjs.com/package/@neutralinojs/lib

Thanks all :)
