### ISSUE TITLE
 Client script upgrade to 3.2.0 prompts an error

### ISSUE THREAD

**Issue by qilecms** [neutralinojs/neutralino.js#41]
![image](https://user-images.githubusercontent.com/13361784/161509731-54b3d844-010f-49e8-a524-a3b9901854e1.png)

![image](https://user-images.githubusercontent.com/13361784/161509598-a1dd9262-5611-4a6c-aca1-c258adf41045.png)

**Comment by shalithasuranga** [comment]
Hello.. Please use the latest versions, then you will be able to see the native method name with the above error message. You can solve the issue by adding the particular method to `nativeAllowList`.

Thanks :tada:
