### ISSUE TITLE
os.execCommand returns error

### ISSUE THREAD

**Issue by shadichy** [neutralinojs/neutralino.js#44]
![image](https://user-images.githubusercontent.com/60534636/163707233-6415a8d9-7049-4d09-9012-04fbb01ffea2.png)

**Comment by pathange-s** [comment]
The following error can be resolved by wrapping await calls in an `async` function. Probably you didn't do that, that's why this error occurred. Add `async` before the function name should help you out.

**Comment by shadichy** [comment]
is there any way to do that (or the same thing) without `async`?

**Comment by pathange-s** [comment]
You could use promises and resolve them.

**Comment by shadichy** [comment]
ok, thanks
sorry for wasting your time

**Comment by pathange-s** [comment]
No issues, glad to help :)
