### ISSUE TITLE
Neutralino Getting Started app does not work properly

### ISSUE THREAD

**Issue by Mrthomas20121** [neutralinojs/neutralino.js#60]
https://cdn.discordapp.com/attachments/747546662423232533/1020324525914734653/unknown.png
I get a white screen when running the Getting Started app with `neu run`.

i already ran CheckNetIsolation.exe LoopbackExempt -a -n="Microsoft.Win32WebViewHost_cw5n1h2txyewy"
and i already have the WebView2 runtime installed
idk what's the issue here

i'm running windows 11 home, version 21H2, build 22000.978

**Comment by saravanan-inc** [comment]
@Mrthomas20121 is the issue resolved
