### ISSUE TITLE
neutralino-linux_x64 was stopped with error code 2 -- default starter app 

### ISSUE THREAD

**Issue by siddharth-narayan** [neutralinojs/neutralino.js#71]
I have no idea why this is happening or how I can debug it. All I have done is follow the Getting Started instructions on the website and I have run into this error. When executing the command `neu run` I get this long error, and the app fails to open: 

```neu: INFO Starting process: neutralino-linux_x64  --load-dir-res --path=. --export-auth-info --neu-dev-extension --neu-dev-auto-reload
bin/neutralino-linux_x64: 1: exception_ZNSt3_V216generic_categoryEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4__ZNSt13runtime_errorC1ERKS__ZNSt14basic_ofstreamIcSt11char_traitsIcEEC1ERKNSt7__cxx1112basic_stringIcS1_SaIcEEESt13_Ios_Openmode_ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE_ZNSt6locale7classicEv_ZSt9terminatev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7_S_moveEPcPKcm_ZNKSt3_V214error_category10_M_messageB5cxx11Ei_ZNSt11logic_errorD2Ev_ZNSirsERi_ZNSirsERj_ZNSirsERl_ZNSirsERm_ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate_ZTVSt12bad_weak_ptr_ZNSt12length_errorC1EPKc_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEmmPKcm_ZTISt11regex_error_ZTISt9exception_ZNSt5ctypeIcE2idE_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5eraseEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9__ZNSt14basic_ifstreamIcSt11char_traitsIcEEC1Ev_ZTISt8bad_cast_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5eraseEmm_ZTIv_ZNSi4peekEv_ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE_ZTISt5ctypeIcE_ZTISt12bad_weak_ptr_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4_mm_ZdlPvm_ZNSt13runtime_errorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_ZNSt6chrono3_V212system_clock3nowEv_ZNSt3_V214error_categoryD2Ev_ZNSt14basic_ifstreamIcSt11char_traitsIcEED0Ev_ZNKSt6locale2id5_M_idEv_ZNSolsEi_ZNSolsEm_ZNSolsEt_ZNSiC1EPSt15basic_streambufIcSt11char_traitsIcEE_ZNSt18condition_variableC1Ev_ZNSt3_V215system_categoryEv_ZNSt12placeholders2_1E_ZSt17current_exceptionv_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofEPKcmm_ZNSi5seekgESt4fposI11__mbstate_tE_ZSt4endlIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6__ZNSt6localeC1ERKS__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm__cxa_guard_acquire_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignEmc_ZNSo9_M_insertImEERSoT__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EOS4__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2EPKcRKS3__ZTVN10__cxxabiv120__function_type_infoE_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6substrEmm_ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS__ZNSt12bad_weak_ptrD1Ev_ZNSt14basic_ifstreamIcSt11char_traitsIcEEC1EPKcSt13_Ios_Openmode_ZSt24__throw_invalid_argumentPKc_ZSt25__throw_bad_function_callv_ZNSi4readEPcl_ZNKSt13runtime_error4whatEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKc_ZNSt13runtime_errorC1EPKc_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED2Ev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9push_backEc_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3__ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base_ZNSt16invalid_argumentD1Ev_ZNSt8ios_base4InitD1Ev_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEPKcm_ZNSt13basic_fstreamIcSt11char_traitsIcEE5closeEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2ERKS4__ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EES4__ZNSo9_M_insertIPKvEERSoT__ZNSi7getlineEPcl_ZTVSt12system_error_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEcm_Znam_ZNSt16invalid_argumentC1EPKc_ZNKSt12__basic_fileIcE7is_openEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendERKS4__ZNSt13basic_fstreamIcSt11char_traitsIcEED0Ev_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE2atEm_ZNSt9bad_allocD1Ev_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode_ZNSt6localeC1Ev__cxa_throw_ZNSt15__exception_ptr13exception_ptrD1Ev_ZTVN10__cxxabiv117__class_type_infoE_ZTVN10__cxxabiv119__pointer_type_infoE_ZSt17__throw_bad_allocv_ZTVN10__cxxabiv120__si_class_type_infoE_ZNSt9exceptionD2Ev_ZTISt12system_error__cxa_begin_catch_ZSt20__throw_system_errori_ZTISt13runtime_error__cxa_guard_abort_ZSt4cerr_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEmc_ZdlPv__cxa_pure_virtual_ZNSt13runtime_errorC2EPKc_ZNKSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strEv_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strERKNS_12basic_stringIcS2_S3_EE_ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EE_ZNSt13runtime_errorC2ERKS__ZSt16__throw_bad_castv__cxa_guard_release_ZNSo9_M_insertIyEERSoT__ZNSt6thread6_StateD2Ev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEOS4__ZTINSt6locale5facetE_ZNSt6localeaSERKS___cxa_allocate_exception_ZNSt6chrono3_V212steady_clock3nowEv__gxx_personality_v0_ZSt9use_facetINSt7__cxx117collateIcEEERKT_RKSt6locale_ZTINSt6thread6_StateE_ZNKSt3_V214error_category10equivalentERKSt10error_codei_ZNKSt9exception4whatEv_ZNSiD1Ev_ZNSt13runtime_errorD1Ev_ZNSt6thread4joinEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEPKc_ZTINSt3_V214error_categoryE_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ERKNS_12basic_stringIcS2_S3_EESt13_Ios_Openmode_ZNSt11logic_errorC2ERKS__ZNSi10_M_extractImEERSiRT__ZNSt15__exception_ptr13exception_ptrC1ERKS0__ZNKSt3_V214error_category23default_error_conditionEi_ZdaPv_ZNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEC1ERKNS_12basic_stringIcS2_S3_EESt13_Ios_Openmode_ZNSt6thread6detachEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKcm_ZNKSt5ctypeIcE13_M_widen_initEv_ZNSo5writeEPKcl_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode_ZNSt13basic_fstreamIcSt11char_traitsIcEEC1EPKcSt13_Ios_Openmode_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcm_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEmc_ZNSt14basic_ofstreamIcSt11char_traitsIcEE5closeEv_ZTISt16invalid_argument_ZTISt11logic_error_ZNKSt11logic_error4whatEv_ZNKSt8__detail20_Prime_rehash_policy14_M_need_rehashEmmm_ZNSt8bad_castD2Ev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2ERKS4_mm_ZTVSt9bad_alloc_ZNSo5flushEv_ZNSt14basic_ifstreamIcSt11char_traitsIcEED1Ev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2EOS4__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4__ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc_ZNSi5tellgEv_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEmmRKS4__ZNSt18condition_variable10notify_oneEv_ZNSt14basic_ifstreamIcSt11char_traitsIcEE4openERKNSt7__cxx1112basic_stringIcS1_SaIcEEESt13_Ios_Openmode_Znwm__cxa_bad_cast_ZNSt15__exception_ptr13exception_ptr4swapERS0___dynamic_cast_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_S_assignEPcmc_ZNSt15__exception_ptr13exception_ptrC1EPv_ZNSt8ios_base4InitC1Ev_ZSt19__throw_regex_errorNSt15regex_constants10error_typeE_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7_S_copyEPcPKcm_ZNSt12system_errorD1Ev_ZNSt18condition_variableD1Ev_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE_ZNSirsEPFRSt8ios_baseS0_E__cxa_rethrow_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEED1Ev_ZSt24__throw_out_of_range_fmtPKcz_ZTVSt11regex_error_ZSt9use_facetISt5ctypeIcEERKT_RKSt6locale_ZTISt9bad_alloc_ZSt18_Rb_tree_incrementPKSt18_Rb_tree_node_base_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm_ZSt28_Rb_tree_rebalance_for_erasePSt18_Rb_tree_node_baseRS__ZNSt9basic_iosIcSt11char_traitsIcEE5imbueERKSt6locale_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLERKS4__ZNKSt7__cxx117collateIcE9transformEPKcS3__ZNSt12length_errorD1Ev_ZTISt12out_of_range_ZNSt15__exception_ptr13exception_ptrC1Ev_ZSt11_Hash_bytesPKvmm_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev_ZTVSt12length_error_ZNSi5seekgElSt12_Ios_Seekdir_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv_ZSt4cout_ZNSt14basic_ofstreamIcSt11char_traitsIcEED1Ev_ZSt20__throw_out_of_rangePKc_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_eraseEmm_ZStlsIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_St8_SetfillIS3_E_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4__ZTISt12length_error_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8__ZNSt11regex_errorD1Ev_ZNKSt3_V214error_category10equivalentEiRKSt15error_condition_ZNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEED1Ev_ZNSt9exceptionD1Ev_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_checkEmPKc__cxa_end_catch_ZNSolsEPFRSt8ios_baseS0_E_ZNSt14basic_ifstreamIcSt11char_traitsIcEE5closeEv_ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base_ZStrsIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EE_ZSt19__throw_logic_errorPKc_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructEmc__cxa_free_exceptionlibgcc_s.so.1_Unwind_Resumelibpthread.so.0pthread_cond_initpthread_mutex_destroyreadpthread_condattr_setclockpthread_sigmaskpthread_mutex_initpthread_cond_waitpthread_cond_destroyrecv__errno_locationpthread_mutex_lockpthread_cond_signalpthread_cond_timedwaitacceptfcntlpthread_cond_broadcastpthread_condattr_initpausepthread_mutex_unlocknanosleeppthread_condattr_destroysendmsgwaitpidpthread_mutex_trylocklibc.so.6epoll_createsocketstrcpyexeclwordexpreaddirexecvsrandwordfreetimerfd_createpipeclosedirepoll_waitinet_ntopforksigfillset__stack_chk_faillistenmkdirstrtoll_exitmemchrtolowerpopengetpidkillinet_ptonstrftime__assert_faillocaltime_risspacestrtodstrtokstrtolexeclefgetsisxdigit__cxa_atexitdirnamelocaleconvisalnumstrstrrmdirbindchdirmemcmptouppereventfddup2shutdownvsnprintfpollgetpwuid_rstrtoulsetsockoptmallocstrcatrealpathremovesetpgidaligned_allocgetpeernameopendirgetenvioctltimerfd_settime__snprintf_chkgetuidexecveexecvpif_nametoindexstrtoullpclosegetcwdif_indextonamegettimeofdayepoll_ctl__memcpy_chkatoiatolstrerror_rstrchrgetsocknameepoll_create1wcstombs__sprintf_chkmemmoveunamestrcmpstrerror__libc_start_mainwcslensysconf__environ__xstat_edata__bss_start_endGCC_3.0GLIBCXX_3.4.18CXXABI_1.3.11GLIBCXX_3.4.14GLIBCXX_3.4.19CXXABI_1.3.5GLIBCXX_3.4.9GLIBCXX_3.4.22CXXABI_1.3.3GLIBCXX_3.4.11GLIBCXX_3.4.15GLIBCXX_3.4.20CXXABI_1.3.9CXXABI_1.3GLIBCXX_3.4.21GLIBCXX_3.4GLIBC_2.2.5GLIBC_2.7GLIBC_2.16GLIBC_2.9GLIBC_2.8GLIBC_2.3GLIBC_2.4GLIBC_2.3.2GLIBC_2.3.4GLIBC_2.3.: File name too long
bin/neutralino-linux_x64: 2: 

: not found
bin/neutralino-linux_x64: 3: : not found
bin/neutralino-linux_x64: 4: Syntax error: word unexpected (expecting ")")
neu: WARNING neutralino-linux_x64 was stopped with error code 2```

**Comment by Sadaf-A** [comment]
> I have no idea why this is happening or how I can debug it. All I have done is follow the Getting Started instructions on the website and I have run into this error. When executing the command `neu run` I get this long error, and the app fails to open:
> 
> ```
> bin/neutralino-linux_x64: 1: exception_ZNSt3_V216generic_categoryEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_assignERKS4__ZNSt13runtime_errorC1ERKS__ZNSt14basic_ofstreamIcSt11char_traitsIcEEC1ERKNSt7__cxx1112basic_stringIcS1_SaIcEEESt13_Ios_Openmode_ZNSt6thread15_M_start_threadESt10unique_ptrINS_6_StateESt14default_deleteIS1_EEPFvvE_ZNSt6locale7classicEv_ZSt9terminatev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7_S_moveEPcPKcm_ZNKSt3_V214error_category10_M_messageB5cxx11Ei_ZNSt11logic_errorD2Ev_ZNSirsERi_ZNSirsERj_ZNSirsERl_ZNSirsERm_ZNSt9basic_iosIcSt11char_traitsIcEE5clearESt12_Ios_Iostate_ZTVSt12bad_weak_ptr_ZNSt12length_errorC1EPKc_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7replaceEmmPKcm_ZTISt11regex_error_ZTISt9exception_ZNSt5ctypeIcE2idE_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5eraseEN9__gnu_cxx17__normal_iteratorIPKcS4_EES9__ZNSt14basic_ifstreamIcSt11char_traitsIcEEC1Ev_ZTISt8bad_cast_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5eraseEmm_ZTIv_ZNSi4peekEv_ZStlsIcSt11char_traitsIcESaIcEERSt13basic_ostreamIT_T0_ES7_RKNSt7__cxx1112basic_stringIS4_S5_T1_EE_ZTISt5ctypeIcE_ZTISt12bad_weak_ptr_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4_mm_ZdlPvm_ZNSt13runtime_errorC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE_ZNSt6chrono3_V212system_clock3nowEv_ZNSt3_V214error_categoryD2Ev_ZNSt14basic_ifstreamIcSt11char_traitsIcEED0Ev_ZNKSt6locale2id5_M_idEv_ZNSolsEi_ZNSolsEm_ZNSolsEt_ZNSiC1EPSt15basic_streambufIcSt11char_traitsIcEE_ZNSt18condition_variableC1Ev_ZNSt3_V215system_categoryEv_ZNSt12placeholders2_1E_ZSt17current_exceptionv_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12find_last_ofEPKcmm_ZNSi5seekgESt4fposI11__mbstate_tE_ZSt4endlIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6__ZNSt6localeC1ERKS__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7reserveEm__cxa_guard_acquire_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6assignEmc_ZNSo9_M_insertImEERSoT__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EOS4__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2EPKcRKS3__ZTVN10__cxxabiv120__function_type_infoE_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6substrEmm_ZSt29_Rb_tree_insert_and_rebalancebPSt18_Rb_tree_node_baseS0_RS__ZNSt12bad_weak_ptrD1Ev_ZNSt14basic_ifstreamIcSt11char_traitsIcEEC1EPKcSt13_Ios_Openmode_ZSt24__throw_invalid_argumentPKc_ZSt25__throw_bad_function_callv_ZNSi4readEPcl_ZNKSt13runtime_error4whatEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKc_ZNSt13runtime_errorC1EPKc_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED2Ev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9push_backEc_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1EPKcRKS3__ZSt18_Rb_tree_incrementPSt18_Rb_tree_node_base_ZNSt16invalid_argumentD1Ev_ZNSt8ios_base4InitD1Ev_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE5rfindEPKcm_ZNSt13basic_fstreamIcSt11char_traitsIcEE5closeEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2ERKS4__ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EES4__ZNSo9_M_insertIPKvEERSoT__ZNSi7getlineEPcl_ZTVSt12system_error_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEcm_Znam_ZNSt16invalid_argumentC1EPKc_ZNKSt12__basic_fileIcE7is_openEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendERKS4__ZNSt13basic_fstreamIcSt11char_traitsIcEED0Ev_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE2atEm_ZNSt9bad_allocD1Ev_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode_ZNSt6localeC1Ev__cxa_throw_ZNSt15__exception_ptr13exception_ptrD1Ev_ZTVN10__cxxabiv117__class_type_infoE_ZTVN10__cxxabiv119__pointer_type_infoE_ZSt17__throw_bad_allocv_ZTVN10__cxxabiv120__si_class_type_infoE_ZNSt9exceptionD2Ev_ZTISt12system_error__cxa_begin_catch_ZSt20__throw_system_errori_ZTISt13runtime_error__cxa_guard_abort_ZSt4cerr_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6resizeEmc_ZdlPv__cxa_pure_virtual_ZNSt13runtime_errorC2EPKc_ZNKSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strEv_ZNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEE3strERKNS_12basic_stringIcS2_S3_EE_ZSt7getlineIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EE_ZNSt13runtime_errorC2ERKS__ZSt16__throw_bad_castv__cxa_guard_release_ZNSo9_M_insertIyEERSoT__ZNSt6thread6_StateD2Ev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEOS4__ZTINSt6locale5facetE_ZNSt6localeaSERKS___cxa_allocate_exception_ZNSt6chrono3_V212steady_clock3nowEv__gxx_personality_v0_ZSt9use_facetINSt7__cxx117collateIcEEERKT_RKSt6locale_ZTINSt6thread6_StateE_ZNKSt3_V214error_category10equivalentERKSt10error_codei_ZNKSt9exception4whatEv_ZNSiD1Ev_ZNSt13runtime_errorD1Ev_ZNSt6thread4joinEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEaSEPKc_ZTINSt3_V214error_categoryE_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEEC1ERKNS_12basic_stringIcS2_S3_EESt13_Ios_Openmode_ZNSt11logic_errorC2ERKS__ZNSi10_M_extractImEERSiRT__ZNSt15__exception_ptr13exception_ptrC1ERKS0__ZNKSt3_V214error_category23default_error_conditionEi_ZdaPv_ZNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEEC1ERKNS_12basic_stringIcS2_S3_EESt13_Ios_Openmode_ZNSt6thread6detachEv_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEPKcm_ZNKSt5ctypeIcE13_M_widen_initEv_ZNSo5writeEPKcl_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEEC1ESt13_Ios_Openmode_ZNSt13basic_fstreamIcSt11char_traitsIcEEC1EPKcSt13_Ios_Openmode_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcm_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE6appendEmc_ZNSt14basic_ofstreamIcSt11char_traitsIcEE5closeEv_ZTISt16invalid_argument_ZTISt11logic_error_ZNKSt11logic_error4whatEv_ZNKSt8__detail20_Prime_rehash_policy14_M_need_rehashEmmm_ZNSt8bad_castD2Ev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2ERKS4_mm_ZTVSt9bad_alloc_ZNSo5flushEv_ZNSt14basic_ifstreamIcSt11char_traitsIcEED1Ev_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC2EOS4__ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEC1ERKS4__ZStlsISt11char_traitsIcEERSt13basic_ostreamIcT_ES5_PKc_ZNSi5tellgEv_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareEmmRKS4__ZNSt18condition_variable10notify_oneEv_ZNSt14basic_ifstreamIcSt11char_traitsIcEE4openERKNSt7__cxx1112basic_stringIcS1_SaIcEEESt13_Ios_Openmode_Znwm__cxa_bad_cast_ZNSt15__exception_ptr13exception_ptr4swapERS0___dynamic_cast_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_S_assignEPcmc_ZNSt15__exception_ptr13exception_ptrC1EPv_ZNSt8ios_base4InitC1Ev_ZSt19__throw_regex_errorNSt15regex_constants10error_typeE_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7_S_copyEPcPKcm_ZNSt12system_errorD1Ev_ZNSt18condition_variableD1Ev_ZSt17rethrow_exceptionNSt15__exception_ptr13exception_ptrE_ZNSirsEPFRSt8ios_baseS0_E__cxa_rethrow_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEED1Ev_ZNSt7__cxx1119basic_ostringstreamIcSt11char_traitsIcESaIcEED1Ev_ZSt24__throw_out_of_range_fmtPKcz_ZTVSt11regex_error_ZSt9use_facetISt5ctypeIcEERKT_RKSt6locale_ZTISt9bad_alloc_ZSt18_Rb_tree_incrementPKSt18_Rb_tree_node_base_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE9_M_mutateEmmPKcm_ZSt28_Rb_tree_rebalance_for_erasePSt18_Rb_tree_node_baseRS__ZNSt9basic_iosIcSt11char_traitsIcEE5imbueERKSt6locale_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEpLERKS4__ZNKSt7__cxx117collateIcE9transformEPKcS3__ZNSt12length_errorD1Ev_ZTISt12out_of_range_ZNSt15__exception_ptr13exception_ptrC1Ev_ZSt11_Hash_bytesPKvmm_ZNSt7__cxx1118basic_stringstreamIcSt11char_traitsIcESaIcEED1Ev_ZTVSt12length_error_ZNSi5seekgElSt12_Ios_Seekdir_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE10_M_disposeEv_ZSt4cout_ZNSt14basic_ofstreamIcSt11char_traitsIcEED1Ev_ZSt20__throw_out_of_rangePKc_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE4findEPKcmm_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_eraseEmm_ZStlsIcSt11char_traitsIcEERSt13basic_ostreamIT_T0_ES6_St8_SetfillIS3_E_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE7compareERKS4__ZTISt12length_error_ZStplIcSt11char_traitsIcESaIcEENSt7__cxx1112basic_stringIT_T0_T1_EEPKS5_RKS8__ZNSt11regex_errorD1Ev_ZNKSt3_V214error_category10equivalentEiRKSt15error_condition_ZNSt7__cxx1119basic_istringstreamIcSt11char_traitsIcESaIcEED1Ev_ZNSt9exceptionD1Ev_ZNKSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE8_M_checkEmPKc__cxa_end_catch_ZNSolsEPFRSt8ios_baseS0_E_ZNSt14basic_ifstreamIcSt11char_traitsIcEE5closeEv_ZSt18_Rb_tree_decrementPSt18_Rb_tree_node_base_ZStrsIcSt11char_traitsIcESaIcEERSt13basic_istreamIT_T0_ES7_RNSt7__cxx1112basic_stringIS4_S5_T1_EE_ZSt19__throw_logic_errorPKc_ZNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEE12_M_constructEmc__cxa_free_exceptionlibgcc_s.so.1_Unwind_Resumelibpthread.so.0pthread_cond_initpthread_mutex_destroyreadpthread_condattr_setclockpthread_sigmaskpthread_mutex_initpthread_cond_waitpthread_cond_destroyrecv__errno_locationpthread_mutex_lockpthread_cond_signalpthread_cond_timedwaitacceptfcntlpthread_cond_broadcastpthread_condattr_initpausepthread_mutex_unlocknanosleeppthread_condattr_destroysendmsgwaitpidpthread_mutex_trylocklibc.so.6epoll_createsocketstrcpyexeclwordexpreaddirexecvsrandwordfreetimerfd_createpipeclosedirepoll_waitinet_ntopforksigfillset__stack_chk_faillistenmkdirstrtoll_exitmemchrtolowerpopengetpidkillinet_ptonstrftime__assert_faillocaltime_risspacestrtodstrtokstrtolexeclefgetsisxdigit__cxa_atexitdirnamelocaleconvisalnumstrstrrmdirbindchdirmemcmptouppereventfddup2shutdownvsnprintfpollgetpwuid_rstrtoulsetsockoptmallocstrcatrealpathremovesetpgidaligned_allocgetpeernameopendirgetenvioctltimerfd_settime__snprintf_chkgetuidexecveexecvpif_nametoindexstrtoullpclosegetcwdif_indextonamegettimeofdayepoll_ctl__memcpy_chkatoiatolstrerror_rstrchrgetsocknameepoll_create1wcstombs__sprintf_chkmemmoveunamestrcmpstrerror__libc_start_mainwcslensysconf__environ__xstat_edata__bss_start_endGCC_3.0GLIBCXX_3.4.18CXXABI_1.3.11GLIBCXX_3.4.14GLIBCXX_3.4.19CXXABI_1.3.5GLIBCXX_3.4.9GLIBCXX_3.4.22CXXABI_1.3.3GLIBCXX_3.4.11GLIBCXX_3.4.15GLIBCXX_3.4.20CXXABI_1.3.9CXXABI_1.3GLIBCXX_3.4.21GLIBCXX_3.4GLIBC_2.2.5GLIBC_2.7GLIBC_2.16GLIBC_2.9GLIBC_2.8GLIBC_2.3GLIBC_2.4GLIBC_2.3.2GLIBC_2.3.4GLIBC_2.3.: File name too long
> bin/neutralino-linux_x64: 2: 
> 
> : not found
> bin/neutralino-linux_x64: 3: : not found
> bin/neutralino-linux_x64: 4: Syntax error: word unexpected (expecting ")")
> neu: WARNING neutralino-linux_x64 was stopped with error code 2```
> ```

hey @siddharth-narayan, I just tried the tutorial it worked fine for me could you provide some more information like the OS you are using and after which step you faced this error?

**Comment by siddharth-narayan** [comment]
On a fresh install of ubuntu in a VM, these are the commands I ran:

```
sudo apt install npm
sudo npm install -g neutralinojs/neu
neu create myapp
```

Here was *an* error right away (because it's a VM I included in image)
![image](https://github.com/neutralinojs/neutralino.js/assets/26383051/f9b24b99-59d8-4065-a4bf-cf7965b2cac8)

**Comment by siddharth-narayan** [comment]
This error seemed easy to fix but I'm pretty sure the original error was a different one. Unfortunately (or fortunately?) I couldn't replicate the original on the virtual machine. After updating the nodejs version to 18, the app started up perfectly. It's totally possible that the original problem was my fault entirely.
